version: '3.8'

services:
  mongodb:
    image: mongo:8.0.1
    container_name: ${MONGO_INITDB_SERVICE_NAME}
    volumes:
      - mongodb_data:/data/${MONGO_INITDB_SERVICE_NAME}
    ports:
      - '${MONGO_INITDB_DATABASE_PORT_EXTERNAL}:${MONGO_INITDB_DATABASE_PORT_INTERNAL}'
volumes:
  mongodb_data: