version: '3.8'

services:
  mongo-init:
      image: mongo:8.0.1
      volumes:
            - ./init-admin.js:/docker-entrypoint-initdb.d/init-admin.js
      env_file:
        - ../.env
      command: sh -c "/usr/bin/mongosh --host ${MONGO_INITDB_SERVICE_NAME} /docker-entrypoint-initdb.d/init-admin.js"

volumes:
  mongodb_data: