version: '3.8'

services:
  mongodb:
    container_name: ${MONGO_INITDB_SERVICE_NAME}
    restart: always
    # restart: on-failure:5
    image: mongo:8.0.1
    # command: mongod --auth
    # command: ["mongod", "--auth", "--replSet", "rs0"]
    command: ["mongod", "--auth", "--replSet", "rs0", "--keyFile", "/etc/mongo/mongodb-keyfile"]
    # command: ["mongod", "--replSet", "rs0"]
    # command: ["mongod", "--auth"]
    volumes:
      - mongodb_data:/data/${MONGO_INITDB_SERVICE_NAME}
      - ../mongodb-keyfile:/etc/mongo/mongodb-keyfile
    ports:
      - '${MONGO_INITDB_DATABASE_PORT_EXTERNAL}:${MONGO_INITDB_DATABASE_PORT_INTERNAL}'
    # command: ["--auth", "--replSet", "rs0"]
    # networks:
    #   - my-network

volumes:
  mongodb_data:

# networks:
#   my-network:
#     driver: bridge