FROM node:22-bullseye

RUN apt-get update && \
    apt-get install -y wget gnupg && \
    wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - && \
    echo "deb [arch=amd64] http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list

# Instalujemy MongoDB Tools
RUN apt-get update && \
    apt-get install -y mongodb-org-tools

# Add fontawsome.tar to the container
COPY fontawesome.tar /usr/local/share/