name: Version Bump

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_REPO_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Configure Git
      run: |
        git config --global user.email "dziewanowski@gmail.com"
        git config --global user.name "Jacaplaca"

    - name: Install dependencies
      run: npm ci
      
    - name: Bump version
      run: |
        # Get current version from package.json
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        
        # Increment patch version using Node.js
        NEW_VERSION=$(node -e "
          const currentVersion = '${CURRENT_VERSION}';
          const [major, minor, patch] = currentVersion.split('.');
          const newVersion = \`\${major}.\${minor}.\${parseInt(patch) + 1}\`;
          console.log(newVersion);
        ")
        
        # Update package.json with new version
        npm version "${NEW_VERSION}" --no-git-tag-version
        
        # Commit and push changes
        git add package.json
        git commit -m "Bump version to ${NEW_VERSION} [skip ci]"
        git tag "v${NEW_VERSION}"
        git push && git push --tags