name: Version Bump

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_REPO_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Configure Git
      run: |
        git config --global user.email "dziewanowski@gmail.com"
        git config --global user.name "Jacaplaca"

    - name: Install dependencies
      run: npm ci
      
    - name: Bump version
      run: |
        # Get current version from package.json
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        
        # Increment patch version
        NEW_VERSION=$(node -p "
          const [major, minor, patch] = '${CURRENT_VERSION}'.split('.');
          `${major}.${minor}.${parseInt(patch) + 1}`
        ")
        
        # Update package.json with new version
        npm version $NEW_VERSION -m "Bump version to %s [skip ci]"
        
        # Push changes back to repository
        git push
        git push --tags 